In [8]:
import pandas as pd
import numpy as np
domain_df = pd.read_csv("initial_data.csv")
domain_df['new_domain'] = 'www.'+ domain_df.domain
domain_df.head(10)

                  domain domain_type                 new_domain
0   wisuolycossttqrj.com         dga   www.wisuolycossttqrj.com
1           wi-wamss.org      benign           www.wi-wamss.org
2   qcxfurnkbqidxxcl.biz         dga   www.qcxfurnkbqidxxcl.biz
3   192-168-1-1-admin.ru      benign   www.192-168-1-1-admin.ru
4    dblsiobnkjxomkmh.ru         dga    www.dblsiobnkjxomkmh.ru
5            su5aksay.ru      benign            www.su5aksay.ru
6         sisalex.edu.eg      benign         www.sisalex.edu.eg
7    vloiolycossttqrj.cn         dga    www.vloiolycossttqrj.cn
8           bmabazar.com      benign           www.bmabazar.com
9  msyxwioqtcpbbypd.info         dga  www.msyxwioqtcpbbypd.info

In [9]:
# Creating feature
#Transforming each character from the domain to vowels.
vowel = ('a','e','i','o','u')
consonant = ('b','c','d','f','g','h','j','k','l','m','n','p','q','r','s','t','v','w','x','y','z')
numbers = (0,1,2,3,4,5,6,7,8,9)
other = (',','-','/','.')

def transform(val):
    vowel = ('a','e','i','o','u')
    consonant = ('b','c','d','f','g','h','j','k','l','m','n','p','q','r','s','t','v','w','x','y','z')
    numbers = ('0','1','2','3','4','5','6','7','8','9')
    other = (',','-','/','.')
    new = ''
    for char in val:
        if char in vowel:
            new += 'v'
        elif char in consonant:
            new += 'c'
        elif char in numbers:
            new += 'n'
        else:
            new += 's'
    return new
domain_df['feature']= domain_df['new_domain'].apply(transform)
domain_df.head(10)

,domain,domain_type,new_domain,feature
0,wisuolycossttqrj.com,dga,www.wisuolycossttqrj.com,cccscvcvvcccvcccccccscvc
1,wi-wamss.org,benign,www.wi-wamss.org,cccscvscvcccsvcc
2,qcxfurnkbqidxxcl.biz,dga,www.qcxfurnkbqidxxcl.biz,cccsccccvcccccvcccccscvc
3,192-168-1-1-admin.ru,benign,www.192-168-1-1-admin.ru,cccsnnnsnnnsnsnsvccvcscv
4,dblsiobnkjxomkmh.ru,dga,www.dblsiobnkjxomkmh.ru,cccsccccvvcccccvccccscv
5,su5aksay.ru,benign,www.su5aksay.ru,cccscvnvccvcscv
6,sisalex.edu.eg,benign,www.sisalex.edu.eg,cccscvcvcvcsvcvsvc
7,vloiolycossttqrj.cn,dga,www.vloiolycossttqrj.cn,cccsccvvvcccvcccccccscc
8,bmabazar.com,benign,www.bmabazar.com,cccsccvcvcvcscvc
9,msyxwioqtcpbbypd.info,dga,www.msyxwioqtcpbbypd.info,cccscccccvvcccccccccsvccv

In [10]:

for i in domain_df.feature:
    #1-gram
    domain_df.loc[domain_df['feature'] == i , 'v'] =i.count('v')
    domain_df.loc[domain_df['feature'] == i , 'c'] =i.count('c')
    domain_df.loc[domain_df['feature'] == i , 'n'] =i.count('n')
    domain_df.loc[domain_df['feature'] == i , 's'] =i.count('s')

    # 2-gram
    domain_df.loc[domain_df['feature'] == i , 'vv'] =i.count('vv')
    domain_df.loc[domain_df['feature'] == i , 'vc'] =i.count('vc')
    domain_df.loc[domain_df['feature'] == i , 'vn'] =i.count('vn')
    domain_df.loc[domain_df['feature'] == i , 'vs'] =i.count('vs')
    domain_df.loc[domain_df['feature'] == i , 'cv'] =i.count('cv')
    domain_df.loc[domain_df['feature'] == i , 'cc'] =i.count('cc')
    domain_df.loc[domain_df['feature'] == i , 'cn'] =i.count('cn')
    domain_df.loc[domain_df['feature'] == i , 'cs'] =i.count('cs')
    domain_df.loc[domain_df['feature'] == i , 'nv'] =i.count('nv')
    domain_df.loc[domain_df['feature'] == i , 'nc'] =i.count('nc')
    domain_df.loc[domain_df['feature'] == i , 'nn'] =i.count('nn')
    domain_df.loc[domain_df['feature'] == i , 'ns'] =i.count('ns')
    domain_df.loc[domain_df['feature'] == i , 'sv'] =i.count('sv')
    domain_df.loc[domain_df['feature'] == i , 'sc'] =i.count('sc')
    domain_df.loc[domain_df['feature'] == i , 'sn'] =i.count('sn')
    domain_df.loc[domain_df['feature'] == i , 'ss'] =i.count('ss')
     # 3-gram
    domain_df.loc[domain_df['feature'] == i , 'vvv'] =i.count('vvv')
    domain_df.loc[domain_df['feature'] == i , 'vcv'] =i.count('vcv')
    domain_df.loc[domain_df['feature'] == i , 'vnv'] =i.count('vnv')
    domain_df.loc[domain_df['feature'] == i , 'vsv'] =i.count('vsv')
    domain_df.loc[domain_df['feature'] == i , 'cvv'] =i.count('cvv')
    domain_df.loc[domain_df['feature'] == i , 'ccv'] =i.count('ccv')
    domain_df.loc[domain_df['feature'] == i , 'cnv'] =i.count('cnv')
    domain_df.loc[domain_df['feature'] == i , 'csv'] =i.count('csv')
    domain_df.loc[domain_df['feature'] == i , 'nvv'] =i.count('nvv')
    domain_df.loc[domain_df['feature'] == i , 'ncv'] =i.count('ncv')
    domain_df.loc[domain_df['feature'] == i , 'nnv'] =i.count('nnv')
    domain_df.loc[domain_df['feature'] == i , 'nsv'] =i.count('nsv')
    domain_df.loc[domain_df['feature'] == i , 'svv'] =i.count('svv')
    domain_df.loc[domain_df['feature'] == i , 'scv'] =i.count('scv')
    domain_df.loc[domain_df['feature'] == i , 'snv'] =i.count('snv')
    domain_df.loc[domain_df['feature'] == i , 'ssv'] =i.count('ssv')
    domain_df.loc[domain_df['feature'] == i , 'vvc'] =i.count('vvc')
    domain_df.loc[domain_df['feature'] == i , 'vcc'] =i.count('vcc')
    domain_df.loc[domain_df['feature'] == i , 'vnc'] =i.count('vnc')
    domain_df.loc[domain_df['feature'] == i , 'vsc'] =i.count('vsc')
    domain_df.loc[domain_df['feature'] == i , 'cvc'] =i.count('cvc')
    domain_df.loc[domain_df['feature'] == i , 'ccc'] =i.count('ccc')
    domain_df.loc[domain_df['feature'] == i , 'cnc'] =i.count('cnc')
    domain_df.loc[domain_df['feature'] == i , 'csc'] =i.count('csc')
    domain_df.loc[domain_df['feature'] == i , 'nvc'] =i.count('nvc')
    domain_df.loc[domain_df['feature'] == i , 'ncc'] =i.count('ncc')
    domain_df.loc[domain_df['feature'] == i , 'nnc'] =i.count('nnc')
    domain_df.loc[domain_df['feature'] == i , 'nsc'] =i.count('nsc')
    domain_df.loc[domain_df['feature'] == i , 'svc'] =i.count('svc')
    domain_df.loc[domain_df['feature'] == i , 'scc'] =i.count('scc')
    domain_df.loc[domain_df['feature'] == i , 'snc'] =i.count('snc')
    domain_df.loc[domain_df['feature'] == i , 'ssc'] =i.count('ssc')
    domain_df.loc[domain_df['feature'] == i , 'vvn'] =i.count('vvn')
    domain_df.loc[domain_df['feature'] == i , 'vcn'] =i.count('vcn')
    domain_df.loc[domain_df['feature'] == i , 'vnn'] =i.count('vnn')
    domain_df.loc[domain_df['feature'] == i , 'vsn'] =i.count('vsn')
    domain_df.loc[domain_df['feature'] == i , 'cvn'] =i.count('cvn')
    domain_df.loc[domain_df['feature'] == i , 'ccn'] =i.count('ccn')
    domain_df.loc[domain_df['feature'] == i , 'cnn'] =i.count('cnn')
    domain_df.loc[domain_df['feature'] == i , 'csn'] =i.count('csn')
    domain_df.loc[domain_df['feature'] == i , 'nvn'] =i.count('nvn')
    domain_df.loc[domain_df['feature'] == i , 'ncn'] =i.count('ncn')
    domain_df.loc[domain_df['feature'] == i , 'nnn'] =i.count('nnn')
    domain_df.loc[domain_df['feature'] == i , 'nsn'] =i.count('nsn')
    domain_df.loc[domain_df['feature'] == i , 'svn'] =i.count('svn')
    domain_df.loc[domain_df['feature'] == i , 'scn'] =i.count('scn')
    domain_df.loc[domain_df['feature'] == i , 'snn'] =i.count('snn')
    domain_df.loc[domain_df['feature'] == i , 'ssn'] =i.count('ssn')
    domain_df.loc[domain_df['feature'] == i , 'vvs'] =i.count('vvs')
    domain_df.loc[domain_df['feature'] == i , 'vcs'] =i.count('vcs')
    domain_df.loc[domain_df['feature'] == i , 'vns'] =i.count('vns')
    domain_df.loc[domain_df['feature'] == i , 'vss'] =i.count('vss')
    domain_df.loc[domain_df['feature'] == i , 'cvs'] =i.count('cvs')
    domain_df.loc[domain_df['feature'] == i , 'ccs'] =i.count('ccs')
    domain_df.loc[domain_df['feature'] == i , 'cns'] =i.count('cns')
    domain_df.loc[domain_df['feature'] == i , 'css'] =i.count('css')
    domain_df.loc[domain_df['feature'] == i , 'nvs'] =i.count('nvs')
    domain_df.loc[domain_df['feature'] == i , 'ncs'] =i.count('ncs')
    domain_df.loc[domain_df['feature'] == i , 'nns'] =i.count('nns')
    domain_df.loc[domain_df['feature'] == i , 'nss'] =i.count('nss')
    domain_df.loc[domain_df['feature'] == i , 'svs'] =i.count('svs')
    domain_df.loc[domain_df['feature'] == i , 'scs'] =i.count('scs')
    domain_df.loc[domain_df['feature'] == i , 'sns'] =i.count('sns')
    domain_df.loc[domain_df['feature'] == i , 'sss'] =i.count('sss')

    #other features
    domain_df.loc[domain_df['feature'] == i ,'length']= len(i)
    domain_df.loc[domain_df['feature'] == i ,'uniqueChar']= len(set(domain_df.loc[domain_df['feature'] == i].domain.to_string()))

In [12]:

X = domain_df.drop(['domain_type','domain','feature','new_domain'], axis=1)
y = domain_df['domain_type']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=575)
X.head(10)

,v,c,n,s,vv,vc,vn,vs,cv,cc,...,nvs,ncs,nns,nss,svs,scs,sns,sss,length,uniqueChar
0,5.0,17.0,0.0,2.0,1.0,4.0,0.0,0.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,35.0
1,3.0,10.0,0.0,3.0,0.0,2.0,0.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,12.0
2,3.0,19.0,0.0,2.0,0.0,3.0,0.0,0.0,3.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,38.0
3,3.0,7.0,8.0,6.0,0.0,2.0,0.0,0.0,2.0,2.0,...,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,24.0,16.0
4,4.0,17.0,0.0,2.0,1.0,2.0,0.0,0.0,3.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,37.0
5,4.0,8.0,1.0,2.0,0.0,2.0,1.0,0.0,3.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,9.0
6,6.0,9.0,0.0,3.0,0.0,5.0,0.0,1.0,4.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,12.0
7,4.0,17.0,0.0,2.0,1.0,2.0,0.0,0.0,2.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,35.0
8,4.0,10.0,0.0,2.0,0.0,4.0,0.0,0.0,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,33.0
9,4.0,19.0,0.0,2.0,1.0,2.0,0.0,0.0,2.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,36.0

In [23]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(X_train, y_train)
y_predict =model.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test,y_predict))
print(classification_report(y_test,y_predict))
pd.crosstab(y_test,y_predict)

0.9995
              precision    recall  f1-score   support

      benign       1.00      1.00      1.00      1995
         dga       1.00      1.00      1.00      2005

    accuracy                           1.00      4000
   macro avg       1.00      1.00      1.00      4000
weighted avg       1.00      1.00      1.00      4000

col_0        benign   dga
domain_type
benign         1995     0
dga               2  2003

In [14]:
# tuning
model2=XGBClassifier(max_depth=2, learning_rate =0.07, random_state =575, n_estimators=200)
model2.fit(X_train, y_train)
y_predict =model2.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test,y_predict))
print(classification_report(y_test,y_predict))
pd.crosstab(y_test,y_predict)

0.99875
              precision    recall  f1-score   support

      benign       1.00      1.00      1.00      1995
         dga       1.00      1.00      1.00      2005

    accuracy                           1.00      4000
   macro avg       1.00      1.00      1.00      4000
weighted avg       1.00      1.00      1.00      4000

col_0        benign   dga
domain_type
benign         1994     1
dga               4  2001

In [31]:
assignment = pd.read_csv("assignment.csv")
assignment['feature']= assignment['domain'].apply(transform)
assignment

,domain,feature
0,www.dutchwebdesign.com,cccscvccccvccvcvccscvc
1,www.pploulsosohvmkv.com,cccscccvvccvcvcccccscvc
2,www.cfsjdqwdhmwkiv.com,cccsccccccccccccvcscvc
3,www.uocoqgiusyeciouaimcauykqswsymo.com,cccsvvcvccvvccvcvvvvvccvvccccccccvscvc
4,www.total-toolbar.com,cccscvcvcscvvccvcscvc
...,...,...
495,www.u23lib5bcxw0yju.com,cccsvnncvcnccccnccvscvc
496,www.prmysangh.com,cccscccccvcccscvc
497,www.ociqkeasqocgoecksu.com,cccsvcvccvvccvccvvcccvscvc
498,www.hj-9.com,cccsccsnscvc
499,www.fpa-be.com,cccsccvscvscvc

In [57]:
def bagofwords(feature):
    df = pd.DataFrame(data=feature)
    for i in feature:
        #1-gram
        df.loc[df['feature'] == i ,'v'] =i.count('v')
        df.loc[df['feature'] == i ,'c'] =i.count('c')
        df.loc[df['feature'] == i ,'n'] =i.count('n')
        df.loc[df['feature'] == i ,'s'] =i.count('s')

        # 2-gram
        df.loc[df['feature'] == i ,'vv'] =i.count('vv')
        df.loc[df['feature'] == i ,'vc'] =i.count('vc')
        df.loc[df['feature'] == i ,'vn'] =i.count('vn')
        df.loc[df['feature'] == i ,'vs'] =i.count('vs')
        df.loc[df['feature'] == i ,'cv'] =i.count('cv')
        df.loc[df['feature'] == i ,'cc'] =i.count('cc')
        df.loc[df['feature'] == i ,'cn'] =i.count('cn')
        df.loc[df['feature'] == i ,'cs'] =i.count('cs')
        df.loc[df['feature'] == i ,'nv'] =i.count('nv')
        df.loc[df['feature'] == i ,'nc'] =i.count('nc')
        df.loc[df['feature'] == i ,'nn'] =i.count('nn')
        df.loc[df['feature'] == i ,'ns'] =i.count('ns')
        df.loc[df['feature'] == i ,'sv'] =i.count('sv')
        df.loc[df['feature'] == i ,'sc'] =i.count('sc')
        df.loc[df['feature'] == i ,'sn'] =i.count('sn')
        df.loc[df['feature'] == i ,'ss'] =i.count('ss')
         # 3-gram
        df.loc[df['feature'] == i ,'vvv'] =i.count('vvv')
        df.loc[df['feature'] == i ,'vcv'] =i.count('vcv')
        df.loc[df['feature'] == i ,'vnv'] =i.count('vnv')
        df.loc[df['feature'] == i ,'vsv'] =i.count('vsv')
        df.loc[df['feature'] == i ,'cvv'] =i.count('cvv')
        df.loc[df['feature'] == i ,'ccv'] =i.count('ccv')
        df.loc[df['feature'] == i ,'cnv'] =i.count('cnv')
        df.loc[df['feature'] == i ,'csv'] =i.count('csv')
        df.loc[df['feature'] == i ,'nvv'] =i.count('nvv')
        df.loc[df['feature'] == i ,'ncv'] =i.count('ncv')
        df.loc[df['feature'] == i ,'nnv'] =i.count('nnv')
        df.loc[df['feature'] == i ,'nsv'] =i.count('nsv')
        df.loc[df['feature'] == i ,'svv'] =i.count('svv')
        df.loc[df['feature'] == i ,'scv'] =i.count('scv')
        df.loc[df['feature'] == i ,'snv'] =i.count('snv')
        df.loc[df['feature'] == i ,'ssv'] =i.count('ssv')
        df.loc[df['feature'] == i ,'vvc'] =i.count('vvc')
        df.loc[df['feature'] == i ,'vcc'] =i.count('vcc')
        df.loc[df['feature'] == i ,'vnc'] =i.count('vnc')
        df.loc[df['feature'] == i ,'vsc'] =i.count('vsc')
        df.loc[df['feature'] == i ,'cvc'] =i.count('cvc')
        df.loc[df['feature'] == i ,'ccc'] =i.count('ccc')
        df.loc[df['feature'] == i ,'cnc'] =i.count('cnc')
        df.loc[df['feature'] == i ,'csc'] =i.count('csc')
        df.loc[df['feature'] == i ,'nvc'] =i.count('nvc')
        df.loc[df['feature'] == i ,'ncc'] =i.count('ncc')
        df.loc[df['feature'] == i ,'nnc'] =i.count('nnc')
        df.loc[df['feature'] == i ,'nsc'] =i.count('nsc')
        df.loc[df['feature'] == i ,'svc'] =i.count('svc')
        df.loc[df['feature'] == i ,'scc'] =i.count('scc')
        df.loc[df['feature'] == i ,'snc'] =i.count('snc')
        df.loc[df['feature'] == i ,'ssc'] =i.count('ssc')
        df.loc[df['feature'] == i ,'vvn'] =i.count('vvn')
        df.loc[df['feature'] == i ,'vcn'] =i.count('vcn')
        df.loc[df['feature'] == i ,'vnn'] =i.count('vnn')
        df.loc[df['feature'] == i ,'vsn'] =i.count('vsn')
        df.loc[df['feature'] == i ,'cvn'] =i.count('cvn')
        df.loc[df['feature'] == i ,'ccn'] =i.count('ccn')
        df.loc[df['feature'] == i ,'cnn'] =i.count('cnn')
        df.loc[df['feature'] == i ,'csn'] =i.count('csn')
        df.loc[df['feature'] == i ,'nvn'] =i.count('nvn')
        df.loc[df['feature'] == i ,'ncn'] =i.count('ncn')
        df.loc[df['feature'] == i ,'nnn'] =i.count('nnn')
        df.loc[df['feature'] == i ,'nsn'] =i.count('nsn')
        df.loc[df['feature'] == i ,'svn'] =i.count('svn')
        df.loc[df['feature'] == i ,'scn'] =i.count('scn')
        df.loc[df['feature'] == i ,'snn'] =i.count('snn')
        df.loc[df['feature'] == i ,'ssn'] =i.count('ssn')
        df.loc[df['feature'] == i ,'vvs'] =i.count('vvs')
        df.loc[df['feature'] == i ,'vcs'] =i.count('vcs')
        df.loc[df['feature'] == i ,'vns'] =i.count('vns')
        df.loc[df['feature'] == i ,'vss'] =i.count('vss')
        df.loc[df['feature'] == i ,'cvs'] =i.count('cvs')
        df.loc[df['feature'] == i ,'ccs'] =i.count('ccs')
        df.loc[df['feature'] == i ,'cns'] =i.count('cns')
        df.loc[df['feature'] == i ,'css'] =i.count('css')
        df.loc[df['feature'] == i ,'nvs'] =i.count('nvs')
        df.loc[df['feature'] == i ,'ncs'] =i.count('ncs')
        df.loc[df['feature'] == i ,'nns'] =i.count('nns')
        df.loc[df['feature'] == i ,'nss'] =i.count('nss')
        df.loc[df['feature'] == i ,'svs'] =i.count('svs')
        df.loc[df['feature'] == i ,'scs'] =i.count('scs')
        df.loc[df['feature'] == i ,'sns'] =i.count('sns')
        df.loc[df['feature'] == i ,'sss'] =i.count('sss')

        #other features
        df.loc[df['feature'] == i ,'length']= len(i)
        df.loc[df['feature'] == i ,'uniqueChar']= len(set(i))
    return df.drop(['feature'], axis=1)

In [58]:
bagofwords(assignment.feature).head()

,v,c,n,s,vv,vc,vn,vs,cv,cc,...,nvs,ncs,nns,nss,svs,scs,sns,sss,length,uniqueChar
0,5.0,15.0,0.0,2.0,0.0,5.0,0.0,0.0,5.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,3.0
1,5.0,16.0,0.0,2.0,1.0,4.0,0.0,0.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,3.0
2,2.0,18.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,3.0
3,15.0,21.0,0.0,2.0,5.0,7.0,0.0,1.0,7.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,3.0
4,6.0,12.0,0.0,3.0,1.0,5.0,0.0,0.0,5.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,3.0

In [59]:
assignment_predict =model.predict(bagofwords(assignment.feature))

In [60]:
assignment['threat']= assignment_predict

In [61]:
assignment.threat.value_counts()

benign    484
dga        16
Name: threat, dtype: int64

In [62]:
assignment.head()

,domain,feature,threat
0,www.dutchwebdesign.com,cccscvccccvccvcvccscvc,benign
1,www.pploulsosohvmkv.com,cccscccvvccvcvcccccscvc,benign
2,www.cfsjdqwdhmwkiv.com,cccsccccccccccccvcscvc,benign
3,www.uocoqgiusyeciouaimcauykqswsymo.com,cccsvvcvccvvccvcvvvvvccvvccccccccvscvc,benign
4,www.total-toolbar.com,cccscvcvcscvvccvcscvc,benign

In [66]:
assignment2 = assignment.drop('feature',axis=1)
assignment2.to_csv('assignment_output.csv', index=False)