In [92]:
import pandas as pd
import numpy as np
import xgboost as xgb

In [93]:
df = pd.read_csv('/Users/patienceidegwu/Documents/Spring Quarter 2020/DS 3/training data.csv',header=0, index_col=False)
df['domain'] = df['domain'].str.replace('www.', '')
df.head(5)

                               domain  threat
0                  dutchwebdesign.com  benign
1                 pploulsosohvmkv.com     dga
2                  cfsjdqwdhmwkiv.com     dga
3  uocoqgiusyeciouaimcauykqswsymo.com     dga
4                   total-toolbar.com  benign

In [94]:
# Creating feature
#Transforming each character from the domain to vowels.
vowel = ('a','e','i','o','u')
consonant = ('b','c','d','f','g','h','j','k','l','m','n','p','q','r','s','t','v','w','x','y','z')
numbers = (0,1,2,3,4,5,6,7,8,9)
other = (',','-','/','.')

def transform(val):
    vowel = ('a','e','i','o','u')
    consonant = ('b','c','d','f','g','h','j','k','l','m','n','p','q','r','s','t','v','w','x','y','z')
    numbers = ('0','1','2','3','4','5','6','7','8','9')
    other = (',','-','/','.')
    new = ''
    for char in val:
        if char in vowel:
            new += 'v'
        elif char in consonant:
            new += 'c'
        elif char in numbers:
            new += 'n'
        else:
            new += 'o'
    return new
df['feature']= df['domain'].apply(transform)

In [95]:
df.head()

,domain,threat,feature
0,dutchwebdesign.com,benign,cvccccvccvcvccocvc
1,pploulsosohvmkv.com,dga,cccvvccvcvcccccocvc
2,cfsjdqwdhmwkiv.com,dga,ccccccccccccvcocvc
3,uocoqgiusyeciouaimcauykqswsymo.com,dga,vvcvccvvccvcvvvvvccvvccccccccvocvc
4,total-toolbar.com,benign,cvcvcocvvccvcocvc

In [96]:
def bagofwords(assignment):
    df = pd.DataFrame(data=assignment.feature)
    for i in assignment.feature:
        #1-gram
        df.loc[df['feature'] == i ,'v'] =i.count('v')
        df.loc[df['feature'] == i ,'c'] =i.count('c')
        df.loc[df['feature'] == i ,'n'] =i.count('n')
        df.loc[df['feature'] == i ,'s'] =i.count('s')

        # 2-gram
        df.loc[df['feature'] == i ,'vv'] =i.count('vv')
        df.loc[df['feature'] == i ,'vc'] =i.count('vc')
        df.loc[df['feature'] == i ,'vn'] =i.count('vn')
        df.loc[df['feature'] == i ,'vs'] =i.count('vs')
        df.loc[df['feature'] == i ,'cv'] =i.count('cv')
        df.loc[df['feature'] == i ,'cc'] =i.count('cc')
        df.loc[df['feature'] == i ,'cn'] =i.count('cn')
        df.loc[df['feature'] == i ,'cs'] =i.count('cs')
        df.loc[df['feature'] == i ,'nv'] =i.count('nv')
        df.loc[df['feature'] == i ,'nc'] =i.count('nc')
        df.loc[df['feature'] == i ,'nn'] =i.count('nn')
        df.loc[df['feature'] == i ,'ns'] =i.count('ns')
        df.loc[df['feature'] == i ,'sv'] =i.count('sv')
        df.loc[df['feature'] == i ,'sc'] =i.count('sc')
        df.loc[df['feature'] == i ,'sn'] =i.count('sn')
        df.loc[df['feature'] == i ,'ss'] =i.count('ss')
         # 3-gram
        df.loc[df['feature'] == i ,'vvv'] =i.count('vvv')
        df.loc[df['feature'] == i ,'vcv'] =i.count('vcv')
        df.loc[df['feature'] == i ,'vnv'] =i.count('vnv')
        df.loc[df['feature'] == i ,'vsv'] =i.count('vsv')
        df.loc[df['feature'] == i ,'cvv'] =i.count('cvv')
        df.loc[df['feature'] == i ,'ccv'] =i.count('ccv')
        df.loc[df['feature'] == i ,'cnv'] =i.count('cnv')
        df.loc[df['feature'] == i ,'csv'] =i.count('csv')
        df.loc[df['feature'] == i ,'nvv'] =i.count('nvv')
        df.loc[df['feature'] == i ,'ncv'] =i.count('ncv')
        df.loc[df['feature'] == i ,'nnv'] =i.count('nnv')
        df.loc[df['feature'] == i ,'nsv'] =i.count('nsv')
        df.loc[df['feature'] == i ,'svv'] =i.count('svv')
        df.loc[df['feature'] == i ,'scv'] =i.count('scv')
        df.loc[df['feature'] == i ,'snv'] =i.count('snv')
        df.loc[df['feature'] == i ,'ssv'] =i.count('ssv')
        df.loc[df['feature'] == i ,'vvc'] =i.count('vvc')
        df.loc[df['feature'] == i ,'vcc'] =i.count('vcc')
        df.loc[df['feature'] == i ,'vnc'] =i.count('vnc')
        df.loc[df['feature'] == i ,'vsc'] =i.count('vsc')
        df.loc[df['feature'] == i ,'cvc'] =i.count('cvc')
        df.loc[df['feature'] == i ,'ccc'] =i.count('ccc')
        df.loc[df['feature'] == i ,'cnc'] =i.count('cnc')
        df.loc[df['feature'] == i ,'csc'] =i.count('csc')
        df.loc[df['feature'] == i ,'nvc'] =i.count('nvc')
        df.loc[df['feature'] == i ,'ncc'] =i.count('ncc')
        df.loc[df['feature'] == i ,'nnc'] =i.count('nnc')
        df.loc[df['feature'] == i ,'nsc'] =i.count('nsc')
        df.loc[df['feature'] == i ,'svc'] =i.count('svc')
        df.loc[df['feature'] == i ,'scc'] =i.count('scc')
        df.loc[df['feature'] == i ,'snc'] =i.count('snc')
        df.loc[df['feature'] == i ,'ssc'] =i.count('ssc')
        df.loc[df['feature'] == i ,'vvn'] =i.count('vvn')
        df.loc[df['feature'] == i ,'vcn'] =i.count('vcn')
        df.loc[df['feature'] == i ,'vnn'] =i.count('vnn')
        df.loc[df['feature'] == i ,'vsn'] =i.count('vsn')
        df.loc[df['feature'] == i ,'cvn'] =i.count('cvn')
        df.loc[df['feature'] == i ,'ccn'] =i.count('ccn')
        df.loc[df['feature'] == i ,'cnn'] =i.count('cnn')
        df.loc[df['feature'] == i ,'csn'] =i.count('csn')
        df.loc[df['feature'] == i ,'nvn'] =i.count('nvn')
        df.loc[df['feature'] == i ,'ncn'] =i.count('ncn')
        df.loc[df['feature'] == i ,'nnn'] =i.count('nnn')
        df.loc[df['feature'] == i ,'nsn'] =i.count('nsn')
        df.loc[df['feature'] == i ,'svn'] =i.count('svn')
        df.loc[df['feature'] == i ,'scn'] =i.count('scn')
        df.loc[df['feature'] == i ,'snn'] =i.count('snn')
        df.loc[df['feature'] == i ,'ssn'] =i.count('ssn')
        df.loc[df['feature'] == i ,'vvs'] =i.count('vvs')
        df.loc[df['feature'] == i ,'vcs'] =i.count('vcs')
        df.loc[df['feature'] == i ,'vns'] =i.count('vns')
        df.loc[df['feature'] == i ,'vss'] =i.count('vss')
        df.loc[df['feature'] == i ,'cvs'] =i.count('cvs')
        df.loc[df['feature'] == i ,'ccs'] =i.count('ccs')
        df.loc[df['feature'] == i ,'cns'] =i.count('cns')
        df.loc[df['feature'] == i ,'css'] =i.count('css')
        df.loc[df['feature'] == i ,'nvs'] =i.count('nvs')
        df.loc[df['feature'] == i ,'ncs'] =i.count('ncs')
        df.loc[df['feature'] == i ,'nns'] =i.count('nns')
        df.loc[df['feature'] == i ,'nss'] =i.count('nss')
        df.loc[df['feature'] == i ,'svs'] =i.count('svs')
        df.loc[df['feature'] == i ,'scs'] =i.count('scs')
        df.loc[df['feature'] == i ,'sns'] =i.count('sns')
        df.loc[df['feature'] == i ,'sss'] =i.count('sss')

               #other features
        df.loc[df['feature'] == i ,'length']= len(i)
        df.loc[df['feature'] == i ,'uniqueChar']= len(set(assignment.loc[assignment['feature'] == i].domain.to_string()))
        df.loc[df['feature'] == i ,'c/v'] = df.c/df.v
        df.loc[df['feature'] == i ,'length/uniC'] = df.length/df.uniqueChar
        df.loc[df['feature'] == i ,'c/length'] = df.c/df.length
        df.loc[df['feature'] == i ,'c/length'] = df.c/df.length
        df.loc[df['feature'] == i ,'v/length'] = df.v/df.length
    return df.drop(['feature'], axis=1)

In [97]:
databow = bagofwords(df)
databow.head()

,v,c,n,s,vv,vc,vn,vs,cv,cc,...,svs,scs,sns,sss,length,uniqueChar,c/v,length/uniC,c/length,v/length
0,5.0,12.0,0.0,0.0,0.0,5.0,0.0,0.0,5.0,4.0,...,0.0,0.0,0.0,0.0,18.0,17.0,2.4,1.058824,0.666667,0.277778
1,5.0,13.0,0.0,0.0,1.0,4.0,0.0,0.0,4.0,4.0,...,0.0,0.0,0.0,0.0,19.0,13.0,2.6,1.461538,0.684211,0.263158
2,2.0,15.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,6.0,...,0.0,0.0,0.0,0.0,18.0,16.0,7.5,1.125000,0.833333,0.111111
3,15.0,18.0,0.0,0.0,5.0,7.0,0.0,0.0,7.0,7.0,...,0.0,0.0,0.0,0.0,34.0,16.0,1.2,2.125000,0.529412,0.441176
4,6.0,9.0,0.0,0.0,1.0,5.0,0.0,0.0,5.0,1.0,...,0.0,0.0,0.0,0.0,17.0,12.0,1.5,1.416667,0.529412,0.352941

In [98]:
y = df['threat']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(databow, y, test_size=0.2, random_state=575)
X_train.head()

,v,c,n,s,vv,vc,vn,vs,cv,cc,...,svs,scs,sns,sss,length,uniqueChar,c/v,length/uniC,c/length,v/length
495,4.0,10.0,4.0,0.0,0.0,2.0,1.0,0.0,3.0,3.0,...,0.0,0.0,0.0,0.0,19.0,19.0,2.500000,1.000000,0.526316,0.210526
20,4.0,8.0,0.0,0.0,1.0,3.0,0.0,0.0,3.0,2.0,...,0.0,0.0,0.0,0.0,13.0,15.0,2.000000,0.866667,0.615385,0.307692
163,13.0,19.0,0.0,0.0,3.0,9.0,0.0,0.0,9.0,5.0,...,0.0,0.0,0.0,0.0,33.0,15.0,1.461538,2.200000,0.575758,0.393939
259,3.0,8.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,2.0,...,0.0,0.0,0.0,0.0,12.0,23.0,2.666667,0.521739,0.666667,0.250000
310,4.0,10.0,0.0,0.0,1.0,2.0,0.0,0.0,2.0,4.0,...,0.0,0.0,0.0,0.0,15.0,15.0,2.500000,1.000000,0.666667,0.266667

In [99]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(X_train, y_train)
y_predict =model.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test,y_predict))
print(classification_report(y_test,y_predict))
pd.crosstab(y_test,y_predict)

0.77
              precision    recall  f1-score   support

      benign       0.73      0.80      0.76        46
         dga       0.82      0.74      0.78        54

    accuracy                           0.77       100
   macro avg       0.77      0.77      0.77       100
weighted avg       0.77      0.77      0.77       100

col_0   benign  dga
threat
benign      37    9
dga         14   40

In [100]:
predict =model.predict(bagofwords(df))

In [101]:
df['predicted']= predict

In [102]:
test=df.drop('feature', axis=1)

In [103]:
test

                                 domain  threat predicted
0                    dutchwebdesign.com  benign    benign
1                   pploulsosohvmkv.com     dga       dga
2                    cfsjdqwdhmwkiv.com     dga       dga
3    uocoqgiusyeciouaimcauykqswsymo.com     dga       dga
4                     total-toolbar.com  benign    benign
..                                  ...     ...       ...
495                 u23lib5bcxw0yju.com     dga       dga
496                       prmysangh.com     dga       dga
497              ociqkeasqocgoecksu.com     dga    benign
498                            hj-9.com  benign    benign
499                          fpa-be.com  benign    benign

[500 rows x 3 columns]

In [104]:
print(accuracy_score(y,predict))

0.908

In [105]:
#y

0      benign
1         dga
2         dga
3         dga
4      benign
        ...
495       dga
496       dga
497       dga
498    benign
499    benign
Name: threat, Length: 500, dtype: object

In [106]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, predict)

In [107]:
cm

array([[215,  18],
       [ 28, 239]])

In [108]:
#cm[1,1]

In [109]:
#cm[0,0]

In [111]:
#(cm[1,1]+cm[0,0])

In [112]:
ratio_correct = ((cm[1,1]+cm[0,0])/(500))

In [113]:
ratio_correct

0.908